[versions]
# Define versions here
springBoot = "3.5.9"
springDependencyManagement = "1.1.7"
spotbugs = "6.0.1"
lombok = "9.1.0"
testcontainers = "1.21.4"

[libraries]
mysql-connector = { group = "com.mysql", name = "mysql-connector-j", version = "9.1.0" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version = "3.1.8" }
testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
testcontainers-mysql = { group = "org.testcontainers", name = "mysql", version.ref = "testcontainers" }


[plugins]
# Format: alias = { id = "...", version.ref = "..." }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }